### PR TITLE
Replaced path instruction by command

### PR DESCRIPTION
**Pull request by NeoTheThird**
That makes it a little easier to follow, since you can just copy the command. People who want to do more complex stuff in their rc will know what to do anyways.
Also added instruction to read new .bashrc

### CODE REVIEW

**Comment by bhdouglass** [comment]
@NeoTheThird thanks! Although wouldn't it be preferable to do `source ~/.bashrc`?

**Comment by bhdouglass** [comment]
Also, I think there are a few other places that needs to be updated.

**Comment by NeoTheThird** [comment]
> @NeoTheThird thanks! Although wouldn't it be preferable to do source ~/.bashrc?

In that case the tilde will get extended to the hard path. Wouldn't cause any immediate problems, but if you were to use your .bashrc on multiple computers w/ different users, it might cause problems. Don't know, if you prefer the tilde, that's also fine with me.

> Also, I think there are a few other places that needs to be updated.

I'll look around.

**Comment by NeoTheThird** [comment]
I think i got 'em all. Since I'm already touching these files, how would you feel about moving the post-install actions directly under the install actions for both options? Esp when using the ppa they can get overlooked by a person in a hurry.

**Comment by bhdouglass** [comment]
I don't see any problem with reading the .bashrc with source, since the user would copy the same command with the tilde for multiple installs it'll expand to the correct path each time.

Yeah, I'm good for moving the stuff around.

**Comment by NeoTheThird** [comment]
> I don't see any problem with reading the .bashrc with source, since the user would copy the same command with the tilde for multiple installs it'll expand to the correct path each time.

Ah, sorry, totally misread the command above. Never check your PRs on the phone while walking XD 

Yeah, i'll add the source instructions. Sorry about that.

> Yeah, I'm good for moving the stuff around.

Ok, coming right up.

**Comment by NeoTheThird** [comment]
Should be fine now

**Comment by NeoTheThird** [comment]
you might want to squash this, though

**Comment by bhdouglass** [comment]
Awesome, thanks!

**Pull request merged**
