### PR TITLE
[WIP] docker: Add experimental Xenial SDK

### PR DESCRIPTION
**Pull request by JBBgameich**
A Xenial SDK will be needed although 15.04 apps also run on Xenial, because some app developers will want to use features of newer Qt versions.
Based on the recipe from usdk-image-tools and the 15.04 dockerfile.
If somebody could send me a sources.list from UBports 16.04, I could most likely finish this PR. The repo.ubports.com structure still confuses me a little bit.

### CODE REVIEW

**Comment by mariogrip** [comment]
Here is source.list
```
# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.

deb http://ports.ubuntu.com/ubuntu-ports/ xenial main restricted
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://ports.ubuntu.com/ubuntu-ports/ xenial-updates main restricted
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://ports.ubuntu.com/ubuntu-ports/ xenial universe
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial universe
deb http://ports.ubuntu.com/ubuntu-ports/ xenial-updates universe
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-updates universe

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
# deb http://ports.ubuntu.com/ubuntu-ports/ xenial-backports main restricted universe
# deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-backports main restricted universe

deb http://ports.ubuntu.com/ubuntu-ports/ xenial-security main restricted
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-security main restricted
deb http://ports.ubuntu.com/ubuntu-ports/ xenial-security universe
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-security universe
# deb http://ports.ubuntu.com/ubuntu-ports/ xenial-security multiverse
# deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-security multiverse
```

And here is the ubports.list (found in source.list.d)
``` 
deb http://repo.ubports.com/ xenial main
```

And lastly here is extra-ppas.list (also found in source.list.d)
```
deb http://ppa.launchpad.net/ci-train-ppa-service/stable-phone-overlay/ubuntu xenial main
deb-src http://ppa.launchpad.net/ci-train-ppa-service/stable-phone-overlay/ubuntu xenial main
```

We still do depend on the ppa a little, but we are working hard to be able to remove the last one, but for now it needs to be there

**Comment by mariogrip** [comment]
Also for qt 5.9, that's not yet been merged into the main xenial repo, so if you want qt 5.9 you need to add

```
deb http://repo.ubports.com/ xenial_-_qt59 main
```

but this will be merged into the main xenial repo a little after ota-3 is out (some bugs that need to be sorted out)

**Comment by bhdouglass** [comment]
@mariogrip thanks!

**Comment by JBBgameich** [comment]
It works now, after removing libertine related dependencies and pinning the overlay PPA like done in usdk-image-tools. Is it correct do do that?

**Comment by JBBgameich** [comment]
I've tried to do the requested changes, but I get dependency problems after pinning repo.ubports.com :/

**Comment by JBBgameich** [comment]
Due to upstream ubuntu dependency problems, I have no Idea how to finish this currently.

**Comment by bhdouglass** [comment]
@JBBgameich I'm going to merge this in as is. We can revisit it in the future when xenial is closer to a reality. I won't publish the image to docker hub, so only the adventurous developer will be able to use it anyways.

**Comment by mariogrip** [comment]
Just tried this now, and seems to work just fine for me

**Comment by JBBgameich** [comment]
Cool, I'll try again then :)

**Comment by JBBgameich** [comment]
Yeah, works for me too now. Maybe Ubuntu or UBports fixed something in their repositories.

**Comment by JBBgameich** [comment]
@bhdouglass It would be quite helpful for me if you could upload the 16.04 docker image, so we can actually use it in clickable.

Alternatively, how can I tell clickable to use some local container image that is not on dockerhub?

**Comment by bhdouglass** [comment]
I'll build it and upload it since it seems more stable now. Until I do you can build it locally and name it correctly to use it with clickable. Should just be able to call it `clickable/ubuntu-sdk:16.04-armhf`.

**Comment by bhdouglass** [comment]
@JBBgameich & @mariogrip I just tried building this today and got this error: `E: Failed to fetch http://repo.ubports.com/pool/xenial/main/q/qtlocation-opensource-src/libqt5location5_5.9.1+dfsg+ubports_armhf.deb  Hash Sum mismatch
`

**Pull request merged**
