### PR TITLE
Add debian packaging

### PR DESCRIPTION
**Pull request by JBBgameich**
I don't know if there is much interest in debian packaging, as there are snaps already, but in case somebody wants it, I open the PR nevertheless.

### CODE REVIEW

**Comment by bhdouglass** [comment]
You are my new favorite person!

Can you have the usdk-target command installed from this repo? The original probably won't get any more updates.

What commands do I need to run to generate a deb for testing?

**Comment by JBBgameich** [comment]
I used your repository https://github.com/bhdouglass/usdk-tools for building usdk-target from source. It's no good practise to include precompiled binaries in debian packages.

For building the deb, you need to have devscripts installed. Simply run `dpkg-buildpackage` and it should generate the deb.

**Comment by JBBgameich** [comment]
Btw, when this (https://wiki.debian.org/LXD) is finished, the package should also work on debian, not only ubuntu.

**Comment by bhdouglass** [comment]
I'm not really familiar with deb packaging, but where does usdk-target get compiled?

**Comment by JBBgameich** [comment]
You already have debian packaging in your usdk-tools repository. You need to build and install that first and then clickable should use usdk-target from the system.

**Comment by bhdouglass** [comment]
Oh duh, I'll have to give that a whirl.

**Comment by bhdouglass** [comment]
thanks so much for doing this! I'll have to setup a ppa a point people towards it.

**Pull request merged**
