### PR TITLE
Python3 and pip install

### PR DESCRIPTION
**Pull request by delijati**
I ported the code to `python3` and made it `pip install` compatible (`setup.py`). It is now possible to install it via:

```
$ pip install -e git+https://github.com/delijati/clickable
$ clickable --help
```

This package should also be registered on https://pypi.python.org/pypi

For further work, restructuring the package should get module aka:
```
- setup.py
- README.md
- clickable/
    - cli.py
    - clickable.py
    - config.py
    - ...
```

### CODE REVIEW

**Comment by JBBgameich** [comment]
The debian packaging also needs to depend on python3 then

**Comment by delijati** [comment]
There are tool to convert a python package (egg) to debian package:
- https://github.com/paylogic/py2deb
- https://github.com/jordansissel/fpm
- https://github.com/spotify/dh-virtualenv
- ...

**Comment by delijati** [comment]
This could than manage the dependency to `cookiecutter` and its deps.

**Comment by JBBgameich** [comment]
Just replace python-cookiecutter with python3-cookiecutter
and python with python3 in debian/control

**Comment by delijati** [comment]
We should also add some `tests`. Currently its changing is a like "blind flying" ;)

**Comment by bhdouglass** [comment]
Wow, this is awesome, thanks @delijati !

Splitting the code up has been on my mind every time I need to scroll up or down the code, it's been getting massive!

I see you updated the build_deb.sh script, but that won't help when building to push to the ppa & launchpad. I think you need to update the debian/install file (but @JBBgameich might have some better insight there). But it does seem like a better idea to use something to convert the python package to a deb.

Yeah, adding tests has been on my todo list, as the code is continuing to grow and it starts getting scarier to make changes!

**Comment by delijati** [comment]
Updated the branch; what blocking the merge?

**Comment by bhdouglass** [comment]
@delijati I believe the outstanding issue is just the naming of the file: https://github.com/bhdouglass/clickable/blob/master/debian/clickable.install#L1
As it stands I don't believe this pull request will build a valid deb file on launchpad.

**Comment by bhdouglass** [comment]
Finally merged this into master, look forward to a new release soon. Thanks so much!

**Pull request merged**
